/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.Conexion;
import IO.Acceso;
import IO.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;

/**
 *
 * @author User
 */
public class frmAccesos extends javax.swing.JDialog {
       
    Usuario usuAux;
    Acceso accesoAux;    
    
    public frmAccesos(javax.swing.JDialog parent, boolean modal, Usuario usu, JDialog padre) {
        super(parent, modal);
        initComponents();        
        
        usuAux = usu;
        
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/molar.png")).getImage());
        
        lblUsuario.setText(usu.getId());
        
        Acceso acc = usu.getAcceso();
        accesoAux = acc;   // Guardo este objeto para ver si hacer update o insert a la tabla
        
        chkPacientes.setSelected(false);
        chkConsultas.setSelected(false);
        chkEstadisticas.setSelected(false);
        chkAgenda.setSelected(false);
        chkReportes.setSelected(false);
        chkPagos.setSelected(false);
        chkOpciones.setSelected(false);
        chkMigracion.setSelected(false);
        
        if(acc != null){
            btnGuardar.setText("Modificar");
            
            chkPacientes.setSelected(acc.isPacientes());
            chkConsultas.setSelected(acc.isConsultas());
            chkEstadisticas.setSelected(acc.isEstadisticas());
            chkAgenda.setSelected(acc.isAgenda());
            chkReportes.setSelected(acc.isReportes());
            chkPagos.setSelected(acc.isPagos());
            chkOpciones.setSelected(acc.isOpciones());
            chkMigracion.setSelected(acc.isMigracion());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkConsultas = new javax.swing.JCheckBox();
        chkEstadisticas = new javax.swing.JCheckBox();
        chkAgenda = new javax.swing.JCheckBox();
        chkReportes = new javax.swing.JCheckBox();
        chkPagos = new javax.swing.JCheckBox();
        chkOpciones = new javax.swing.JCheckBox();
        chkPacientes = new javax.swing.JCheckBox();
        chkMigracion = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accesos de Usuario");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario:");

        lblEdad.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(51, 51, 51));
        lblEdad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblUsuario.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(622, 622, 622)
                .addComponent(lblEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lblEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        chkConsultas.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkConsultas.setText(" Consultas Médicas");

        chkEstadisticas.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkEstadisticas.setText(" Estadísticas");
        chkEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstadisticasActionPerformed(evt);
            }
        });

        chkAgenda.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkAgenda.setText(" Agenda");
        chkAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAgendaActionPerformed(evt);
            }
        });

        chkReportes.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkReportes.setText(" Reportes");

        chkPagos.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkPagos.setText(" Pagos");

        chkOpciones.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkOpciones.setText(" Opciones");

        chkPacientes.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkPacientes.setText(" Pacientes");

        chkMigracion.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        chkMigracion.setText(" Migración");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMigracion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPacientes)
                    .addComponent(chkConsultas)
                    .addComponent(chkEstadisticas)
                    .addComponent(chkAgenda))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkReportes)
                    .addComponent(chkPagos)
                    .addComponent(chkOpciones)
                    .addComponent(chkMigracion))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios32.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(951, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstadisticasActionPerformed

    private void chkAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAgendaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        Acceso accAux = new Acceso();

        accAux.setUsuario(usuAux);
        accAux.setAgenda(chkAgenda.isSelected());
        accAux.setConsultas(chkConsultas.isSelected());
        accAux.setEstadisticas(chkEstadisticas.isSelected());
        accAux.setOpciones(chkOpciones.isSelected());
        accAux.setPacientes(chkPacientes.isSelected());
        accAux.setPagos(chkPagos.isSelected());
        accAux.setReportes(chkReportes.isSelected());
        accAux.setMigracion(chkMigracion.isSelected());
        
        if(accesoAux != null){
            Conexion.getInstance().Actualizar(accAux);
        }else{
            Conexion.getInstance().Guardar(accAux);
        }
        
        Conexion.getInstance().Combinar(usuAux);
        
        JOptionPane.showMessageDialog(this, "Debe reiniciar sesión para que los cambios se confirmen", "Accesos de Usuario", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkAgenda;
    private javax.swing.JCheckBox chkConsultas;
    private javax.swing.JCheckBox chkEstadisticas;
    private javax.swing.JCheckBox chkMigracion;
    private javax.swing.JCheckBox chkOpciones;
    private javax.swing.JCheckBox chkPacientes;
    private javax.swing.JCheckBox chkPagos;
    private javax.swing.JCheckBox chkReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
