/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.Conexion;
import IO.Opcion;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class frmBaseDeDatos extends javax.swing.JDialog {

    Date fecha = new Date();
    SimpleDateFormat df = new SimpleDateFormat();
    String fchHoy = df.format(fecha.getDate()).toString();
    
    public frmBaseDeDatos(javax.swing.JDialog parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();    
        
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/molar.png")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRestauraBUp = new javax.swing.JButton();
        btnRealizaBUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración de la Base de Datos");
        setResizable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/postgresql.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnRestauraBUp.setBackground(new java.awt.Color(0, 102, 204));
        btnRestauraBUp.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRestauraBUp.setForeground(new java.awt.Color(255, 255, 255));
        btnRestauraBUp.setText("Restaurar BackUp");
        btnRestauraBUp.setBorder(null);
        btnRestauraBUp.setBorderPainted(false);
        btnRestauraBUp.setFocusPainted(false);
        btnRestauraBUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauraBUpActionPerformed(evt);
            }
        });

        btnRealizaBUp.setBackground(new java.awt.Color(0, 102, 204));
        btnRealizaBUp.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRealizaBUp.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizaBUp.setText("Realizar BackUp");
        btnRealizaBUp.setBorder(null);
        btnRealizaBUp.setBorderPainted(false);
        btnRealizaBUp.setFocusPainted(false);
        btnRealizaBUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizaBUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRealizaBUp, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(btnRestauraBUp, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestauraBUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRealizaBUp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(982, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestauraBUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauraBUpActionPerformed
        
        Opcion op = Conexion.getInstance().getOpciones().unaOpcion("2");
        
        JFileChooser jFileChooser1 =  new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("BackUp", "backup");
        jFileChooser1.setFileFilter(filter);
        
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File archivo = jFileChooser1.getSelectedFile();
            String nomeDoArquivo = jFileChooser1.getName(archivo);
            Conexion.getInstance().getProcedimientos().RestaurarBD(jFileChooser1.getSelectedFile().getPath(), nomeDoArquivo);
        }
//        if(op != null){
//            String dir = op.getValor(); 
//            
//            Conexion.getInstance().getProcedimientos().RestaurarBD(jFileChooser1.getSelectedFile().getPath());
//        }else{
//            JOptionPane.showMessageDialog(this, "No existe path parametrizado para realizar el BackUp. Darlo de alta bajo el identificador nro. 2", "Error", JOptionPane.ERROR_MESSAGE);
//        }        
    }//GEN-LAST:event_btnRestauraBUpActionPerformed

    private void btnRealizaBUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizaBUpActionPerformed
        
        // En la opción con el identificador 2 se parametriza la carpeta donde va a quedar el backup de la base de datos
        Opcion op = Conexion.getInstance().getOpciones().unaOpcion("2");
        
        if(op != null){
            String dir = op.getValor();  
        
            Conexion.getInstance().getProcedimientos().realizaBackup(dir);  // Obtengo el directorio parametrizado y se lo paso como parametro
        }else{
            JOptionPane.showMessageDialog(this, "No existe path parametrizado para realizar el BackUp. Darlo de alta bajo el identificador nro. 2", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRealizaBUpActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizaBUp;
    private javax.swing.JButton btnRestauraBUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
